namespace: kube-system
helmCharts:
  - namespace: kube-system
    version: 39.0.0
    releaseName: traefik
    name:  traefik
    valuesFile: values.yml
    repo: https://traefik.github.io/charts
    includeCRDs: true
resources:
  - ingress-route.yml
