helmCharts:
  - repo: https://charts.jetstack.io
    version: v1.19.2
    name: cert-manager
    releaseName: cert-manager
    valuesFile: values.yaml
    namespace: cert-manager
    includeCRDs: true

resources:
  - namespace.yml