namespace: longhorn-system
helmCharts:
  - namespace: longhorn-system
    repo: https://charts.longhorn.io
    name: longhorn
    releaseName: longhorn
    version: 1.10.2
    includeCRDs: true
    valuesFile: values.yml

resources:
  - namespace.yml
  - ingress.yml
